global:
  scrape_interval: 15s # Scrape targets every 15 seconds
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/rules.yml" # Path to our alerting rules

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093'] # Tells Prometheus where AlertManager is

scrape_configs:
  - job_name: 'prometheus'
    # Scrape Prometheus itself to monitor its health
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend_app'
    static_configs:
      - targets: ['backend_app:8000'] 

  - job_name: 'node_exporter'
    # Scrape the exporter for host machine metrics (CPU, RAM, etc.)
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cadvisor'
    # Scrape the exporter for per-container metrics
    static_configs:
      - targets: ['cadvisor:8080']